### ISSUE TITLE
Support tracking checkboxes with [%] and [/]

### ISSUE THREAD

**Issue by bezmi** [orgzly/orgzly-android#547]
- [x] I have searched for existing issues that may be the same as or related to mine. In the orgmode manual [checkboxes](https://orgmode.org/manual/Checkboxes.html) page, we see this:

* TODO Organize party [2/4]
  - [-] call people [1/3]
    - [ ] Peter
    - [x] Sarah
    - [ ] Sam
  - [X] order food
  - [ ] think about what music to play
  - [X] talk to the **neighbors**

I rely on this feature, as well as the "%" version to track smaller sub-tasks within a main TODO item. Could this be implemented in orgzly? I'm thinking that there could be a "x % completed" or "x/y completed" displayed below the heading, where the deadline/scheduled dates are shown.

**Comment by nevenz** [comment]
It's #311, thanks.

**Comment by bezmi** [comment]
Apologies, I searched but did not know this feature was called cookies.
